#!/usr/bin/env python

import argparse
import subprocess

class GenomeBrowser(object):
    def __init__(self):
        pass

class Cligb(GenomeBrowser):
    def __init__(self):
        GenomeBrowser.__init__(self)
        
        
    def parse_args(self):
        parser = argparse.ArgumentParser(description='cligb: Command line based genome browser for *-seq data')
        parser.add_argument('--bam_dir|-b', type=str, dest="bam_dir", required=True)
        parser.add_argument('--symbol', type=str, dest="symbol", required=True)
        return parser.parse_args()

if __name__ == '__main__':
    cligb = Cligb()
    args = cligb.parse_args()
    R_code = "gb2.R"
    subprocess.call("R --vanilla --slave -f {} --args {} {}".format(R_code, args.symbol, args.bam_dir), shell=True)
    
    
    
    
    
    
